### ISSUE TITLE
Missing the required redirect URI

### ISSUE THREAD

**Issue by lllyx1** [idk-tn/yii2-google-apiclient#7]
Exception 'InvalidArgumentException' with message 'missing the required redirect URI'

Launching through the console, an error occurs when entering Available scopes 
"Available scopes :
  https://www.googleapis.com/auth/spreadsheets          See, edit, create, and delete all your Google Sheets spreadsheets
  https://www.googleapis.com/auth/drive.file            See, edit, create, and delete only the specific Google Drive files you use with this app
  https://www.googleapis.com/auth/drive.readonly                See and download all your Google Drive files
  https://www.googleapis.com/auth/drive         See, edit, create, and delete all of your Google Drive files
  https://www.googleapis.com/auth/spreadsheets.readonly         See all your Google Sheets spreadsheets"

I write the url and I get an error

Full error: 

in E:\OpenServer\domains\mo.loc\vendor\google\auth\src\OAuth2.php:694

Stack trace:
#0 E:\OpenServer\domains\mo.loc\vendor\google\apiclient\src\Client.php(404): Google\Auth\OAuth2->buildFullAuthorizationUri()
#1 E:\OpenServer\domains\mo.loc\vendor\idk\yii2-google-apiclient\commands\GoogleController.php(218): Google\Client->createAuthUrl()
#2 E:\OpenServer\domains\mo.loc\vendor\idk\yii2-google-apiclient\commands\GoogleController.php(145): idk\yii2\google\apiclient\commands\GoogleController->generateCredentialsFile()
#3 [internal function]: idk\yii2\google\apiclient\commands\GoogleController->actionConfigure()
#4 E:\OpenServer\domains\mo.loc\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array()
#5 E:\OpenServer\domains\mo.loc\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams()
#6 E:\OpenServer\domains\mo.loc\vendor\yiisoft\yii2\console\Controller.php(180): yii\base\Controller->runAction()
#7 E:\OpenServer\domains\mo.loc\vendor\yiisoft\yii2\base\Module.php(552): yii\console\Controller->runAction()
#8 E:\OpenServer\domains\mo.loc\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction()
#9 E:\OpenServer\domains\mo.loc\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction()
#10 E:\OpenServer\domains\mo.loc\vendor\yiisoft\yii2\base\Application.php(384): yii\console\Application->handleRequest()
#11 E:\OpenServer\domains\mo.loc\yii(20): yii\base\Application->run()
#12 {main}

**Comment by machour** [comment]
Hey,

Can you show your complete terminal logs, including the commands you issued, etc?
